const nations = [
  {value:'GABON',label:'가봉'},
  {value:'GREECE',label:'그리스'},
  {value:'NIGERIA',label:'나이지리아'},
  {value:'SOUTHAFRICA',label:'남아프리카'},
  {value:'NETHERLANDS',label:'네덜란드'},
  {value:'NEPAL',label:'네팔'},
  {value:'NORWAY',label:'노르웨이'},
  {value:'NEWZEALAND',label:'뉴질랜드'},
  {value:'NEWCALEDONIA',label:'뉴칼레도니아'},
  {value:'TAIWAN',label:'대만'},
  {value:'DENMARK',label:'덴마크'},
  {value:'DOMINICA',label:'도미니카'},
  {value:'GERMANY',label:'독일'},
  {value:'LAOS',label:'라오스'},
  {value:'LATVIA',label:'라트비아'},
  {value:'RUSSIANFEDERATION',label:'러시아'},
  {value:'LEBANON',label:'레바논'},
  {value:'ROMANIA',label:'루마니아'},
  {value:'RWANDA',label:'르완다'},
  {value:'LUXEMBOURE',label:'룩셈부르크'},
  {value:'LIBYANARABJAMAHIRIYA',label:'리비아'},
  {value:'MARSHALLISLANDS',label:'마셜제도'},
  {value:'MACAU',label:'마카오'},
  {value:'MALAYSIA',label:'말레이시아'},
  {value:'MEXICO',label:'멕시코'},
  {value:'MOROCCO',label:'모로코'},
  {value:'MALDIVES',label:'몰디브공화국'},
  {value:'MALTA',label:'몰타공화국'},
  {value:'MONGOLIA',label:'몽고'},
  {value:'USA',label:'미국'},
  {value:'MYANMAR',label:'미얀마'},
  {value:'MICRONESIA',label:'미크로네시아'},
  {value:'BAHRAIN',label:'바레인'},
  {value:'BANGLADESH',label:'방글라데시'},
  {value:'VENEZUELA',label:'베네수엘라'},
  {value:'VIETNAM',label:'베트남'},
  {value:'BELGIUM',label:'벨기에'},
  {value:'BHUTAN',label:'부탄'},
  {value:'NORTHKOREA',label:'북한'},
  {value:'BULGARIA',label:'불가리아'},
  {value:'BRAZIL',label:'브라질'},
  {value:'BRUNEIDARUSSALAM',label:'브루나이'},
  {value:'SAUDIARABIA',label:'사우디아라비아'},
  {value:'SENEGAL',label:'세네갈'},
  {value:'SOMALIA',label:'소말리아'},
  {value:'SUDAN',label:'수단'},
  {value:'SRILANKA',label:'스리랑카'},
  {value:'SWEDEN',label:'스웨덴'},
  {value:'SWITZERLAND',label:'스위스'},
  {value:'SPAIN',label:'스페인'},
  {value:'SLOVAKIA',label:'슬로바키아'},
  {value:'SINGAPORE',label:'싱가포르'},
  {value:'UNITEDARABEMIRATES',label:'아랍에미레이트'},
  {value:'ICELAND',label:'아이슬랜드'},
  {value:'IRELAND',label:'아일랜드'},
  {value:'AZERBAIJAN',label:'아제르바이잔'},
  {value:'AFGHANISTAN',label:'아프가니스탄'},
  {value:'ALGERIA',label:'알제리'},
  {value:'ANGOLA',label:'앙골라'},
  {value:'ESTONIA',label:'에스토니아'},
  {value:'UNITEDKINGDOM',label:'영국'},
  {value:'YEMEN',label:'예맨'},
  {value:'OMAN',label:'오만'},
  {value:'AUSTRIA',label:'오스트리아'},
  {value:'JORDAN',label:'요르단'},
  {value:'UZBEKISTAN',label:'우즈베키스탄'},
  {value:'UKRAINE',label:'우크라이나'},
  {value:'ETHIOPIA',label:'이디오피아'},
  {value:'IRAQ',label:'이라크'},
  {value:'IRAN',label:'이란'},
  {value:'ISRAEL',label:'이스라엘'},
  {value:'EGYPT',label:'이집트'},
  {value:'ITALY',label:'이탈리아'},
  {value:'INDIA',label:'인도'},
  {value:'INDONESIA',label:'인도네시아'},
  {value:'JAPAN',label:'일본'},
  {value:'CHINA',label:'중국'},
  {value:'CENTRALAFRICANREPUBLIC',label:'중앙아프리카'},
  {value:'DJIBOUTI',label:'지부티'},
  {value:'CZECHREP',label:'체코'},
  {value:'CHILE',label:'칠레'},
  {value:'KAZAKHSTAN',label:'카자흐스탄'},
  {value:'QATAR',label:'카타르'},
  {value:'COMBODIA',label:'캄보디아'},
  {value:'CANADA',label:'캐나다'},
  {value:'KENYA',label:'케냐'},
  {value:'COLOMBIA',label:'콜롬비아'},
  {value:'GUATEMALA',label:'콰테말라'},
  {value:'KUWAIT',label:'쿠웨이트'},
  {value:'CROATIA',label:'크로아티아'},
  {value:'KYRGYZSTAN',label:'키르기즈스탄'},
  {value:'CYPRUS',label:'키프로스'},
  {value:'TANZANIA',label:'탄자니아'},
  {value:'THAILAND',label:'태국'},
  {value:'TURKEY',label:'터키'},
  {value:'TURKMENISTAN',label:'투르크매니스탄'},
  {value:'TUNISIA',label:'튀니지'},
  {value:'PANAMA',label:'파나마'},
  {value:'PAKISTAN',label:'파키스탄'},
  {value:'PAPUANEWGUINEA',label:'파푸아뉴기니'},
  {value:'PERU',label:'페루'},
  {value:'PORTUGAL',label:'포르투갈'},
  {value:'POLAND',label:'폴란드'},
  {value:'FRANCE',label:'프랑스'},
  {value:'FIJI',label:'피지'},
  {value:'FINLAND',label:'핀란드'},
  {value:'PHILIPPINES',label:'필리핀'},
  {value:'KOREA',label:'한국'},
  {value:'HUNGARY',label:'헝가리'},
  {value:'AUSTRALIA',label:'호주'},
  {value:'HONGKONG',label:'홍콩'},
  
];

const citys = {
    가봉: [
      {value: '1', label: '1'},
      {value: '2', label: '2'},
      {value: '3', label: '3'},
      {value: '4', label: '4'},
      {value: '5', label: '5'},
      {value: '6', label: '6'},
    ]
};

export { nations, citys } ;
