# Generated by Django 2.1.1 on 2018-09-23 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to=settings.AUTH_USER_MODEL),
        ),
    ]
