# Generated by Django 2.1.1 on 2018-09-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180923_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
