# Generated by Django 2.1.2 on 2018-10-23 16:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20180929_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
