# Generated by Django 2.1.2 on 2018-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20181024_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='travel_region',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
