# Generated by Django 2.1.2 on 2018-10-25 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_travel_travel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='travel_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travel_region',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
