# Generated by Django 2.1.2 on 2018-10-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20181025_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['-updated_at']},
        ),
    ]
