# Generated by Django 2.1.2 on 2018-10-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20181026_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelplan',
            options={'ordering': ['-travel_day']},
        ),
    ]
