# Generated by Django 2.1.2 on 2018-11-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20181030_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_plan', to='travel.Travel'),
        ),
    ]
