# Generated by Django 2.1.2 on 2018-11-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('0', '시작하기'), ('1', '여행 중'), ('2', '추억하기')], default='0', max_length=1),
        ),
    ]
