# Generated by Django 2.1.2 on 2018-11-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels_todo', to='travel.Travel'),
        ),
    ]
